from enum import Enum


class MetricEvent(Enum):
    REQUEST = "REQUEST"
    HIT = "HIT"
    MISS = "MISS"
    RESPONSE_REUSED = "RESPONSE_REUSED"
    RETRIEVAL_REUSED = "RETRIEVAL_REUSED"
    LOCAL_CACHE_HIT = "LOCAL_CACHE_HIT"
    DISTRIBUTED_CACHE_HIT = "DISTRIBUTED_CACHE_HIT"
    REMOTE_RESPONSE_REUSED = "REMOTE_RESPONSE_REUSED"
    REMOTE_RETRIEVAL_REUSED = "REMOTE_RETRIEVAL_REUSED"
    DISTRIBUTED_MISS = "DISTRIBUTED_MISS"
    DISTRIBUTED_SYNC = "DISTRIBUTED_SYNC"
    DISTRIBUTED_SYNC_FAILURE = "DISTRIBUTED_SYNC_FAILURE"
    DISTRIBUTED_BACKEND_FAILURE = "DISTRIBUTED_BACKEND_FAILURE"
    DISTRIBUTED_INVALID_RECORD = "DISTRIBUTED_INVALID_RECORD"
    FALLBACK_TO_LOCAL = "FALLBACK_TO_LOCAL"
    DISTRIBUTED_LOCK_ACQUIRED = "DISTRIBUTED_LOCK_ACQUIRED"
    DISTRIBUTED_LOCK_CONTENTION = "DISTRIBUTED_LOCK_CONTENTION"
    DISTRIBUTED_LOCK_TIMEOUT = "DISTRIBUTED_LOCK_TIMEOUT"
    DUPLICATE_WORK_AVOIDED = "DUPLICATE_WORK_AVOIDED"
